// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddImageTag(arg1, arg2) {
  return window['go']['main']['App']['AddImageTag'](arg1, arg2);
}

export function AddPromptVersion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddPromptVersion'](arg1, arg2, arg3, arg4);
}

export function AdvancedSearch(arg1) {
  return window['go']['main']['App']['AdvancedSearch'](arg1);
}

export function AppendReverseLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['AppendReverseLog'](arg1, arg2, arg3);
}

export function CancelProxyRequest(arg1) {
  return window['go']['main']['App']['CancelProxyRequest'](arg1);
}

export function CleanOrphanedThumbs() {
  return window['go']['main']['App']['CleanOrphanedThumbs']();
}

export function ClearFolderThumbs(arg1) {
  return window['go']['main']['App']['ClearFolderThumbs'](arg1);
}

export function DebugAppState() {
  return window['go']['main']['App']['DebugAppState']();
}

export function DebugPagination(arg1) {
  return window['go']['main']['App']['DebugPagination'](arg1);
}

export function DebugScanRoot(arg1) {
  return window['go']['main']['App']['DebugScanRoot'](arg1);
}

export function DeletePromptVersion(arg1) {
  return window['go']['main']['App']['DeletePromptVersion'](arg1);
}

export function FullRescanFolder(arg1) {
  return window['go']['main']['App']['FullRescanFolder'](arg1);
}

export function GetAllFavorites() {
  return window['go']['main']['App']['GetAllFavorites']();
}

export function GetAllImageTags() {
  return window['go']['main']['App']['GetAllImageTags']();
}

export function GetAllPromptVersionCounts() {
  return window['go']['main']['App']['GetAllPromptVersionCounts']();
}

export function GetAllPromptVersions() {
  return window['go']['main']['App']['GetAllPromptVersions']();
}

export function GetAllSidebarSettings() {
  return window['go']['main']['App']['GetAllSidebarSettings']();
}

export function GetAllUserData() {
  return window['go']['main']['App']['GetAllUserData']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetFolderCount(arg1) {
  return window['go']['main']['App']['GetFolderCount'](arg1);
}

export function GetFolderIndexStatus() {
  return window['go']['main']['App']['GetFolderIndexStatus']();
}

export function GetFolderProgress(arg1) {
  return window['go']['main']['App']['GetFolderProgress'](arg1);
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetHTTPBaseURL() {
  return window['go']['main']['App']['GetHTTPBaseURL']();
}

export function GetImageBaseURL() {
  return window['go']['main']['App']['GetImageBaseURL']();
}

export function GetImageFile(arg1) {
  return window['go']['main']['App']['GetImageFile'](arg1);
}

export function GetImageTags(arg1) {
  return window['go']['main']['App']['GetImageTags'](arg1);
}

export function GetImages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetImages'](arg1, arg2, arg3, arg4);
}

export function GetImagesByPaths(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetImagesByPaths'](arg1, arg2, arg3, arg4);
}

export function GetImagesForTagIds(arg1) {
  return window['go']['main']['App']['GetImagesForTagIds'](arg1);
}

export function GetImportedRoots() {
  return window['go']['main']['App']['GetImportedRoots']();
}

export function GetLANInfo() {
  return window['go']['main']['App']['GetLANInfo']();
}

export function GetPreGenStatus() {
  return window['go']['main']['App']['GetPreGenStatus']();
}

export function GetPromptVersions(arg1) {
  return window['go']['main']['App']['GetPromptVersions'](arg1);
}

export function GetReverseLog() {
  return window['go']['main']['App']['GetReverseLog']();
}

export function GetSidebarSetting(arg1) {
  return window['go']['main']['App']['GetSidebarSetting'](arg1);
}

export function GetThumbBaseURL2() {
  return window['go']['main']['App']['GetThumbBaseURL2']();
}

export function GetThumbCacheInfo() {
  return window['go']['main']['App']['GetThumbCacheInfo']();
}

export function GetThumbConcurrency() {
  return window['go']['main']['App']['GetThumbConcurrency']();
}

export function GetThumbDir() {
  return window['go']['main']['App']['GetThumbDir']();
}

export function GetThumbGeneration() {
  return window['go']['main']['App']['GetThumbGeneration']();
}

export function GetThumbKernel() {
  return window['go']['main']['App']['GetThumbKernel']();
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function GetUserDataDir() {
  return window['go']['main']['App']['GetUserDataDir']();
}

export function GetWindowState() {
  return window['go']['main']['App']['GetWindowState']();
}

export function ImportImageTags(arg1) {
  return window['go']['main']['App']['ImportImageTags'](arg1);
}

export function ImportPromptVersions(arg1) {
  return window['go']['main']['App']['ImportPromptVersions'](arg1);
}

export function IndexRoot(arg1) {
  return window['go']['main']['App']['IndexRoot'](arg1);
}

export function IsFavorite(arg1) {
  return window['go']['main']['App']['IsFavorite'](arg1);
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function OpenReverseLog() {
  return window['go']['main']['App']['OpenReverseLog']();
}

export function ParseMetadata(arg1) {
  return window['go']['main']['App']['ParseMetadata'](arg1);
}

export function ParseMetadataFast(arg1) {
  return window['go']['main']['App']['ParseMetadataFast'](arg1);
}

export function PausePreGenThumbs() {
  return window['go']['main']['App']['PausePreGenThumbs']();
}

export function PickIconFile() {
  return window['go']['main']['App']['PickIconFile']();
}

export function PreloadThumbCounts() {
  return window['go']['main']['App']['PreloadThumbCounts']();
}

export function ProxyRequest(arg1) {
  return window['go']['main']['App']['ProxyRequest'](arg1);
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function RefreshAll() {
  return window['go']['main']['App']['RefreshAll']();
}

export function RefreshFolder(arg1) {
  return window['go']['main']['App']['RefreshFolder'](arg1);
}

export function RemoveFolder(arg1) {
  return window['go']['main']['App']['RemoveFolder'](arg1);
}

export function RemoveImageTag(arg1, arg2) {
  return window['go']['main']['App']['RemoveImageTag'](arg1, arg2);
}

export function RemoveImageTagsByTagID(arg1) {
  return window['go']['main']['App']['RemoveImageTagsByTagID'](arg1);
}

export function RemoveImages(arg1) {
  return window['go']['main']['App']['RemoveImages'](arg1);
}

export function RescanFolder(arg1) {
  return window['go']['main']['App']['RescanFolder'](arg1);
}

export function ResumePreGenThumbs() {
  return window['go']['main']['App']['ResumePreGenThumbs']();
}

export function SaveAvatar(arg1) {
  return window['go']['main']['App']['SaveAvatar'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveRoots(arg1) {
  return window['go']['main']['App']['SaveRoots'](arg1);
}

export function SaveRootsWithMeta(arg1) {
  return window['go']['main']['App']['SaveRootsWithMeta'](arg1);
}

export function SaveUserData(arg1) {
  return window['go']['main']['App']['SaveUserData'](arg1);
}

export function SaveWindowState(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveWindowState'](arg1, arg2, arg3, arg4, arg5);
}

export function ScanFolder(arg1, arg2) {
  return window['go']['main']['App']['ScanFolder'](arg1, arg2);
}

export function ScanFolderQuick(arg1, arg2, arg3) {
  return window['go']['main']['App']['ScanFolderQuick'](arg1, arg2, arg3);
}

export function SearchImages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchImages'](arg1, arg2, arg3, arg4);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetContext(arg1) {
  return window['go']['main']['App']['SetContext'](arg1);
}

export function SetFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetFavorite'](arg1, arg2);
}

export function SetSidebarSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSidebarSetting'](arg1, arg2);
}

export function SetThumbConcurrency(arg1) {
  return window['go']['main']['App']['SetThumbConcurrency'](arg1);
}

export function SetThumbDir(arg1) {
  return window['go']['main']['App']['SetThumbDir'](arg1);
}

export function SetThumbKernel(arg1) {
  return window['go']['main']['App']['SetThumbKernel'](arg1);
}

export function SetUserDataDir(arg1) {
  return window['go']['main']['App']['SetUserDataDir'](arg1);
}

export function StartFileDrag(arg1) {
  return window['go']['main']['App']['StartFileDrag'](arg1);
}

export function StartLANServer(arg1) {
  return window['go']['main']['App']['StartLANServer'](arg1);
}

export function StartPreGenThumbs(arg1) {
  return window['go']['main']['App']['StartPreGenThumbs'](arg1);
}

export function StopIndexRoot(arg1) {
  return window['go']['main']['App']['StopIndexRoot'](arg1);
}

export function StopLANServer() {
  return window['go']['main']['App']['StopLANServer']();
}

export function StopPreGenThumbs() {
  return window['go']['main']['App']['StopPreGenThumbs']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}
