// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {database} from '../models';
import {context} from '../models';

export function AddImageTag(arg1:string,arg2:string):Promise<Record<string, any>>;

export function AddPromptVersion(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function AdvancedSearch(arg1:main.AdvancedSearchRequest):Promise<main.AdvancedSearchResponse>;

export function AppendReverseLog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CancelProxyRequest(arg1:string):Promise<void>;

export function CleanOrphanedThumbs():Promise<Record<string, any>>;

export function ClearFolderThumbs(arg1:string):Promise<Record<string, any>>;

export function DebugAppState():Promise<Record<string, any>>;

export function DebugPagination(arg1:string):Promise<Record<string, any>>;

export function DebugScanRoot(arg1:string):Promise<main.DebugScanResult>;

export function DeletePromptVersion(arg1:string):Promise<Record<string, any>>;

export function FullRescanFolder(arg1:string):Promise<main.ScanResult>;

export function GetAllFavorites():Promise<Array<string>>;

export function GetAllImageTags():Promise<Array<database.ImageTag>>;

export function GetAllPromptVersionCounts():Promise<Record<string, number>>;

export function GetAllPromptVersions():Promise<Array<database.PromptVersion>>;

export function GetAllSidebarSettings():Promise<Record<string, any>>;

export function GetAllUserData():Promise<Record<string, any>>;

export function GetAppVersion():Promise<string>;

export function GetFolderCount(arg1:string):Promise<number>;

export function GetFolderIndexStatus():Promise<Array<main.IndexRootInfo>>;

export function GetFolders():Promise<Array<main.FolderNode>>;

export function GetHTTPBaseURL():Promise<string>;

export function GetImageBaseURL():Promise<string>;

export function GetImageFile(arg1:string):Promise<main.FileData>;

export function GetImageTags(arg1:string):Promise<Array<database.ImageTag>>;

export function GetImages(arg1:string,arg2:number,arg3:number,arg4:string):Promise<main.ImageListResult>;

export function GetImagesByPaths(arg1:Array<string>,arg2:number,arg3:number,arg4:string):Promise<main.ImageListResult>;

export function GetImagesForTagIds(arg1:Array<string>):Promise<Array<string>>;

export function GetImportedRoots():Promise<Array<database.ImportedRoot>>;

export function GetLANInfo():Promise<Record<string, any>>;

export function GetPreGenStatus():Promise<main.PreGenStatus>;

export function GetPromptVersions(arg1:string):Promise<Array<database.PromptVersion>>;

export function GetReverseLog():Promise<string>;

export function GetSidebarSetting(arg1:string):Promise<Record<string, any>>;

export function GetThumbBaseURL2():Promise<string>;

export function GetThumbCacheInfo():Promise<Record<string, any>>;

export function GetThumbConcurrency():Promise<number>;

export function GetThumbDir():Promise<string>;

export function GetThumbGeneration():Promise<number>;

export function GetThumbKernel():Promise<string>;

export function GetThumbnail(arg1:string):Promise<main.FileData>;

export function GetUserDataDir():Promise<string>;

export function GetWindowState():Promise<main.WindowState>;

export function ImportImageTags(arg1:Array<database.ImageTag>):Promise<Record<string, any>>;

export function ImportPromptVersions(arg1:Array<database.PromptVersion>):Promise<Record<string, any>>;

export function IndexRoot(arg1:string):Promise<void>;

export function IsFavorite(arg1:string):Promise<boolean>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function OpenReverseLog():Promise<void>;

export function ParseMetadata(arg1:string):Promise<Record<string, any>>;

export function ParseMetadataFast(arg1:string):Promise<Record<string, any>>;

export function PausePreGenThumbs():Promise<Record<string, any>>;

export function PickIconFile():Promise<string>;

export function PreloadThumbCounts():Promise<void>;

export function ProxyRequest(arg1:main.ProxyRequestArgs):Promise<Record<string, any>>;

export function Refresh():Promise<main.ScanResult>;

export function RefreshAll():Promise<Record<string, any>>;

export function RefreshFolder(arg1:string):Promise<main.FolderDiffResult>;

export function RemoveFolder(arg1:string):Promise<main.ScanResult>;

export function RemoveImageTag(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RemoveImageTagsByTagID(arg1:string):Promise<Record<string, any>>;

export function RemoveImages(arg1:Array<string>):Promise<Record<string, any>>;

export function RescanFolder(arg1:string):Promise<main.ScanResult>;

export function ResumePreGenThumbs():Promise<Record<string, any>>;

export function SaveAvatar(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SaveRoots(arg1:Array<string>):Promise<Record<string, any>>;

export function SaveRootsWithMeta(arg1:Array<database.ImportedRoot>):Promise<Record<string, any>>;

export function SaveUserData(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SaveWindowState(arg1:number,arg2:number,arg3:number,arg4:number,arg5:boolean):Promise<void>;

export function ScanFolder(arg1:string,arg2:string):Promise<main.ScanResult>;

export function ScanFolderQuick(arg1:string,arg2:string,arg3:boolean):Promise<main.ScanResult>;

export function SearchImages(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.SearchResponse>;

export function SelectFolder():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetFavorite(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function SetSidebarSetting(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SetThumbConcurrency(arg1:number):Promise<Record<string, any>>;

export function SetThumbDir(arg1:string):Promise<Record<string, any>>;

export function SetThumbKernel(arg1:string):Promise<Record<string, any>>;

export function SetUserDataDir(arg1:string):Promise<Record<string, any>>;

export function StartFileDrag(arg1:string):Promise<void>;

export function StartLANServer(arg1:number):Promise<Record<string, any>>;

export function StartPreGenThumbs(arg1:Array<string>):Promise<Record<string, any>>;

export function StopIndexRoot(arg1:string):Promise<void>;

export function StopLANServer():Promise<void>;

export function StopPreGenThumbs():Promise<Record<string, any>>;

export function ToggleFavorite(arg1:string):Promise<Record<string, any>>;
